server:
  port: 8880

spring:
  main:
    web-application-type : reactive
  application:
    name: api-gateway
    open:
      api:
        end-points: >
          /authentication-api/v1/user,
          /user-profile-api/v1/user,
          /news-api/v1/,
          /eureka
  # Config server Configuration
  config:
    import: optional:configserver:http://localhost:8888
    


  cloud:
    gateway:
      routes:
        - id: user-profile-service
          uri: http://localhost:8082
          predicates:
            - Path=/user-profile-api/v1/**
        - id: news-service
          uri: http://localhost:8083
          predicates:
            - Path=/news-api/v1/**
        - id: wishlist-service
          uri: http://localhost:8084
          predicates:
            - Path=/wishlist-api/v1/**
          filters:
            - AuthFilter #filter for validation of token
        - id: authentication
          uri: http://localhost:8085
          predicates:
            - Path=/authentication-api/v1/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

# JWT Secret Token Configuration
jwt:
  secret: secret
  message: Authenticated successfully