spring:
  application:
    name: authentication
  # Mongo DB Configuration
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/user
  datasource:
    driver-class-name: mongodb.jdbc.MongoDriver
  # Config server Configuration
  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:8888

  # Kafka Consumer Configuration
  kafka:
    topic-name: news-app-user-topic
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    consumer:
      group-id: producer-1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
# actuator/Management end-point Configuration
management:
  endpoints:
    web:
      exposure:
        include: refresh

# JWT Secret Token Configuration
jwt:
  secret: secret
  message: Authenticated successfully
# server port Configuration
server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:8761/eureka

